### ISSUE TITLE
Publish to plugin portal

### ISSUE THREAD

**Issue by JLLeitschuh** [GradleWeaver/better-build-file-names#1]
Blocked by the plugin portal:
```
Execution failed for task ':publishPlugins'.
> Failed to post to server.
  Server responded with:
  'org.gradleweaver.plugins.better-build-file-names' cannot be used as plugin ID because it has one of the following prefixes: org.gradle, com.gradle, com.gradleware
```

A possible workaround is to publish to jfrog temporarily.

**Comment by Octogonapus** [comment]
Is this a bug with the plugin portal? It certainly _does_ have that prefix, but it seems to me that they should look for a prefix split on periods.

**Comment by JLLeitschuh** [comment]
> Is this a bug with the plugin portal?

It is. @eriwen has told me that there's a bug that's been filed internally against the Gradle Plugin Portal to fix this eventually.

**Comment by Vampire** [comment]
Was it in the meantime? :-)

**Comment by JLLeitschuh** [comment]
It should now be published, AFAIK.
